module.exports = {
  iconMap: {
    'sell5.htm': 'shopping_cart',
    'salesflat_review.htm': 'assessment',
    'franchiseagency.htm': 'paid',
    'stocklevels.htm': 'inventory_2',
    'Home': 'home',
    'Settings': 'settings',
    'Cart': 'shopping_cart',
    'Receipt': 'receipt',
    'Account': 'account_circle',
    'Store': 'store',
    'Dashboard': 'dashboard',
    'Info': 'info',
    'Help': 'help',
    'Email': 'email',
    'Camera': 'camera_alt',
    'Lock': 'lock',
    'Security': 'security',
    'Build': 'build',
    'Star': 'star',
    'Favorite': 'favorite',
    'Group': 'group',
    'Event': 'event',
    'Assessment': 'assessment',
    'Visibility': 'visibility',
    'Language': 'language',
    'Select Store': 'storefront',
    'Franchise': 'business',
    'Report': 'bar_chart',
    'Products': 'inventory',
    'Loyalty': 'card_membership',
    'Customers': 'people',
    'Suppliers': 'local_shipping',
    'Prepay': 'payment',
    'Pricing': 'attach_money',
    'End of Day': 'schedule',
    'Sales Reports': 'insights',
    'Selling': 'point_of_sale',
    'Franchisee': 'badge',
    'Accounts': 'account_balance',
    'Reports': 'insert_chart',
    'Staff': 'supervisor_account',
    'Stores': 'store',
    'Lanes': 'view_list',
    'Interfaces': 'settings_input_component',
    'Advisor': 'support_agent',
    'Technical': 'engineering',
    'Operations': 'work',
    'Monitoring': 'monitor_heart',
    'API': 'code',
    'Transaction Log': 'receipt_long',
    'Request Journal': 'book',
    'System Commanding': 'terminal',
    'Addins': 'extension',
    'Experimental': 'science',
    'Signs and Labels': 'label',
    'Fieldpine Account': 'account_box',
    'Take Photograph': 'photo_camera',
    'Industry Specific': 'business_center',
    'Vehicles': 'directions_car',
    'Optional Extras': 'add_circle_outline',
    'Memberships': 'how_to_reg',
    'Stocktake': 'fact_check',
    'Service and Repairs': 'build_circle',
    'Industry Benchmarks': 'leaderboard',
    'Franchise Report': 'bar_chart',
    'Email & Interfaces': 'alternate_email',
    'Operations Monitoring': 'monitor_heart',
    'Physical Machines': 'computer',
    'Manage Profiles': 'person',
    'Add New Lane': 'road',
    'CW Web Site': 'store',
    'Sales KPI': 'show_chart',
    'Product List': 'two_pager_store',
    'Purchase Orders': 'inactive_order',
    'Add New Product': 'box_add',
    'Stock Levels': 'inventory_2',
    'Aus Wide': 'sports_cricket',
    'Price Check': 'price_check',

    // Newly added from dump.txt
    'Markdown Pricing': 'attach_money',
    'Department by Store': 'store',
    'Identify Groups': 'group',
    'Store Pricing': 'store',
    'Store Transfers': 'store',
    'Store Replen': 'store',
    'Manage Suppliers': 'local_shipping',
    'Manage Brands': 'branding_watermark',
    'Manage Modifiers': 'tune',
    'Manage Departments': 'corporate_fare',
    'Writeoff Summary': 'delete_sweep',
    'Cost Changes': 'price_change',
    'Pareto Rank': 'leaderboard',
    'Product Upload': 'upload_file',
    'Upload Documents': 'file_upload',
    'Price Map Management': 'map',
    'Movement Transaction Report': 'bar_chart',
    'Product Analysis': 'analytics',
    'Top Selling': 'star_rate',
    'Sales by Month': 'calendar_month',
    'Department Revenue': 'savings',
    'Good Movements': 'bar_chart',
    'Price Cloud Visualisation': 'cloud',
    'Description Visualisation': 'description',
    'PriceGroups': 'groups',
    'PriceBand Maps': 'layers',
    'Discounts': 'percent',
    'Coupon Offers': 'local_offer',
    'Trading Summary': 'receipt_long',
    'Payments List': 'payments',
    'Payment Totals by Period': 'calculate',
    'Serial Items': 'qr_code_2',
    'New Campaign': 'campaign',
    'Add New Customer': 'person_add',
    'Customer Upload': 'upload',
    'Special Uploads': 'upload_special',
    'Derived Customers': 'diversity_3',
    'Statistics': 'bar_chart',
    'Sales History': 'history',
    'Contact Management': 'contact_page',
    'Sales Summary': 'summarize',
    'Inbound Orders': 'move_to_inbox'
  }
};
